# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - run: mvn -s .circleci.settings.xml package
      - setup_remote_docker
      - run: ./build_docker.sh
      - run: mvn -s .circleci.settings.xml verify

