# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - run: mvn -s .circleci.settings.xml package
      - run: docker-compose -f consul.yml build
      - run: mvn -s .circleci.settings.xml verify
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push misqos/greeting
      - run: docker push misqos/visits
